version: '2'
services:
  back:
    build: ./backend
    environment:
      - DB_URL=db
      - DB_USERNAME=projectuser
      - DB_PASSWORD=Passw0rd_1
      - DB_NAME=backdb
    ports:
      - "8080:8080"
